# image will be published to ghcr.io/<user>/<name>
name: ublue-kinoite-6-light
# description will be included in the image's metadata
description: Ublue kinoite minimal with plasma 6

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 40 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be 
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README

  - type: rpm-ostree
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-40.noarch.rpm

  - type: rpm-ostree
    install:
      - podman
      - htop
      - distrobox
      - google-noto-sans-balinese-fonts
      - google-noto-sans-cjk-fonts
      - google-noto-sans-javanese-fonts
      - google-noto-sans-sundanese-fonts
      - smartmontools
      - openssl
      - heif-pixbuf-loader
      - libheif-freeworld
      - libheif-tools
      - libratbag-ratbagd
      - libva-utils
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - kmousetool
      - krfb-libs
      - krfb
      - mariadb-backup
      - mariadb-cracklib-password-check
      - mariadb-common
      - mariadb-server-utils
      - mariadb-server
      - mariadb-errmsg
      - mariadb-gssapi-server
      - mariadb
      - filelight
      - mariadb-connector-c
      - mariadb-connector-c-config
      - perl-DBD-MariaDB
      - qt6-qtbase-mysql
      - akonadi-server-mysql
      - akonadi-server

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
      #system:
      # If no repo information is specified, Flathub will be used by default
      #repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      #repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      #install:
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      #remove:
      # - org.gnome.eog
    #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - org.mozilla.firefox
        - org.kde.kcalc
        - org.kde.gwenview
        - org.kde.okular
        - org.kde.filelight

  - type: systemd
    user:
      enabled:
        - podman.service
        - podman-auto-update.timer
    system:
      masked:
        - libvirt.service

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-signing.noarch.rpm /
      - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-update-services.noarch.rpm /
      - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-udev-rules.noarch.rpm /
      - RUN rpm -ivh /ublue-os-signing.noarch.rpm && rpm -ivh /ublue-os-udev-rules.noarch.rpm && rpm -ivh /ublue-os-update-services.noarch.rpm

  - type: script
    scripts:
      - kinoite.sh
      - kinoite-6.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

