name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout template
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.FORK_SYNC_TOKEN }}
          fetch-depth: 0
      - name: git setup
        run: |
          git config user.name "Vietchinh GitHub Actions Bot"
          git config user.email "1348151+vietchinh@users.noreply.github.com"
      - name: Add blue-build template remote
        run: git remote add main https://github.com/blue-build/template
      - name: Fetch all
        run: git fetch --all
      - name: Checkout template
        run: git checkout -b main --track origin/main
      - name: Check if there is an update available
        id: check
        run: |
          DIFF_COUNT=`git diff --numstat --minimal main/main..main | cut -c1-1`
          if [ -z "$DIFF_COUNT" ]; then
              echo "update=false" >> $GITHUB_ENV
          else
              echo "update=true" >> $GITHUB_ENV
          fi
      - name: Git merge changes from main to ubluelight/main
        if: ${{ env.update == 'true' }}
        run: git merge main/main --allow-unrelated-histories && git push origin main
